schema_version: 1

context:
  version: "0.3.3"

package:
  name: ansicolor
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ansicolor/ansicolor-${{ version }}.tar.gz
  sha256: 6de60837fb322b9fb8c8863061504688520bd0aa62defab43dbf4f2c011dafda

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - ansicolor
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: A library to produce ansi color output and colored highlighting and diffing
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/numerodix/ansicolor

extra:
  recipe-maintainers:
    - danielnachun
